service: sistema-hera-api

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  profile: aws-profile
  region: us-east-1
  memorySize: 128
  timeout: 30
  environment:

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

functions:
  app:
    handler: ./src/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'